spring:
	aplication:
		name: servicio-usuarios
server:
	port: $(PORT:())

eureka:
	client:
		service-url:
			defaultZone: http://localhost:8761/eureka
	  instance:
			instance-id: $(spring.aplication.name):$(spring.aplication.instance_id:$(random.value))

loggin:
	level:
		org:
			hibernate:
				SQL: debug
