spring:
  application:
    name: servicio-zuul-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    store:
      service-id: service-store
      path: /api/tienda/**
    celulares:
      service-id: service-celulares
      path: /api/phone /**
		users:
			service-id: service-usuarios
			path: /api/us/**
		oauth:
			service-id: service-oauth
			path: /api/security/**
ribbon:
  connectTimeout: 3000
  readtimeout: 10000
Hystrix:
  commnad:
    defaut:
      execution:
          isolation:
              thread:
                 timeoutInMilliseconds: 20000

