server:
  port: 8082
spring:
  application:
    name: service-store
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
ribbon:
  connectTimeout: 3000
  readtimeout: 10000
Hystrix:
  commnad:
    defaut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

